# -*- coding: utf-8 -*-
"""Resumo Dicionários + Códigos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ph3Uc1a2NEitJd3xgqmKowScUqNM60nx

## ***Coleções***
"""

# variáveis que conseguem armazenar e reconhecer vários tipos de dados.
# Listas, Tuplas, Dicionários.

palavras = ["carro", "bicicleta", "avião", "barco"] # imprimir como Lista em python.
print(palavras) # ISSO É UMA LISTA.
# Reconhecida por ser uma coleção ordenada e mutável;
# Permitem membros duplicados.

print("-"*30) # divisor fácil

for palavra in palavras: # imprimir separadamente, listado.
  print(palavra)

print(type(palavras)) # "type()" informa o tipo de variável.

print(palavras[1])

# Tuplas.
# Característica visual da Tupla é utilizar parenteses, ao invés de colchetes ou chaves.
# Coleção ordenada, que também permitem membros duplicados;
# Imutáveis.

tupla = ("Carro", True, 2, 3.5)
print(tupla)
print(type(tupla))
print(tupla[3])

# Dicionários.
# Uso de chaves.
# chave: valor.
# Coleções ordenadas, mutáveis e não permitem membros duplicados.
# não tem indice, mas os valores são acessados pelas chaves.

dicionario = {"nome": "carro", "lógica":  True, "numérica": 2, "outro número": 3.5}
print(dicionario)
print(type(dicionario))
print(dicionario["outro número"])

for dic in dicionario:
  print(dic)

for dic in dicionario.values():
  print(dic)

for dic in dicionario.items():
  print(dic)

# para adicionar dicionário a lista, usamos "lista.append(dic)"
# para percorrer uma lista de dicionários, pode-se usar "range(len(lista))".

# Set/Conjunto.
# Uso de chaves.
# Coleção não ordenada e não indexada (não possui indice)
# Nenhum membro duplicado.

conjunto = {"Carro", True, 2, 3.5}
print(conjunto)
print(type(conjunto))

"""## **LIVE**"""

# Live 10/11 - Dicionários.

# -> coleções de pares chave: valor, permitindo organizar dados de forma estruturada.

# Cada valor é acessado por uma chave única, semelhante ao uso de índices em listas
# mas com nomes personalizados.

# Chave: identifica o dado (ex.: "nome")
# Valor: dado associado a chave (ex.: "Fulano")

# As chaves devem ser únicas e podem ser strings, números ou tuplas.
# Os valore podem ser de qualquer tipo: números, strings, listas, outros dicionários, etc.

# Os dicionários:
# Organizam diferentes atributos relacionadors (ex.: informações de estudantes) em um único objeto.
#Flexibilidade: Adicionam, removem e atualizam dados facilmente.

# Dicionários embutidos

# Permitem que um dicionário seja um valor dentro de outros dicionários.
# Útil para representar relaçôes hierárquicas, como "todo" e "partes".
# Entretanto podem levar a dados duplicados ou inconsistentes se múltiplos itens usarem informações repetidas.

dic_estudantes = {
    "nome": "Maria",
    "nota": 9,
    "responsável": {
      "nome": "José",
      "cpf": "123.456.789-10"
    }
}

# Note que esse exemplo usa "=" para atribuir um valor a uma chave
dic_estudante = {}
dic_estudante["nome"] = "Fulano"
dic_estudante["nota"] = 8
dic_estudante["ponto"] = 1
dic_estudante["final"] = dic_estudante["nota"] + dic_estudante["ponto"]

print(dic_estudante)

# Note que:
# 1) a manipulação de um valor de uma chave é => dicionário["chave"]
# 2) a chave "final" foi calculada a partir da soma das chaves "nota" e "ponto"
dic_estudante = {}
dic_estudante["nome"] = input("Digite o nome do estudante : ")
dic_estudante["nota"] = float(input("Digite a nota do estudante : "))
dic_estudante["ponto"] = float(input("Digite o ponto extra do estudante : "))
dic_estudante["final"] = dic_estudante["nota"] + dic_estudante["ponto"] # (1) e (2)

print(dic_estudante)

# Note que:
# 1) esse exemplo usa ":" e "=" para atribuir um valor a uma chave
# 2) a variável "final" foi calculada a partir da soma das chaves "nota" e "ponto"
# 3) a chave "final" foi inserida em estudante considerando o valor da variável "final"
dic_estudante = {"nome" : "Fulano", # (1)
"nota" : 8, # (1)
"ponto" : 1} # (1)

final = dic_estudante["nota"] + dic_estudante["ponto"] # (2)

dic_estudante["final"] = final # (1) e (3)

print(dic_estudante)

"""# **FUNÇÕES P/ MANIPULAR DICIONÁRIOS**"""

# len()
# Retorna a quantidade de chaves que existem no dicionário.

dic_estudante = {"nome" : "Fulano",
"nota" : 8,
"ponto" : 1}

final = dic_estudante["nota"] + dic_estudante["ponto"]

dic_estudante["final"] = final

qtd = len(dic_estudante)
print(qtd, "chaves") # vai exibir 4 chaves

# get()
# Retorna o valor de uma chave.

dic_estudante = {"nome" : "Fulano",
"nota" : 8,
"ponto" : 1}

# get() -> retorna o valor de uma chave
# Se a chave não existir, é retornado None
valor = dic_estudante.get("xpto")
print("nome =", valor) # Vai exibir nome = None

# setdefault()
# Retorna um valor padrão caso a chave não exista.

dic_estudante = {"nome" : "Fulano",
"nota" : 8,
"ponto" : 1}

# setdefault() -> retorna um valor padrão caso a chave não exista
bonus = dic_estudante.setdefault("bonos", 0)
print(bonus) # Vai exibir 0

# in
# Testa se uma chave existe no dicionário.

dic_estudante = {"nome" : "Fulano",
"nota" : 8,
"ponto" : 1}

# in -> testa se uma chave existe no dicionário
print("xpto" in dic_estudante.keys()) # Vai exibir False

# keys()
# Retorna uma lista (dict_keys) que contém as chaves de um dicionário.

dic_estudante = {"nome" : "Fulano",
"nota" : 8,
"ponto" : 1}

# keys() -> retorna uma lista (dict_keys) que contém as chaves de um dicionário
chaves = dic_estudante.keys()
print(chaves) # Vai exibir dict_keys(['nome', 'nota', 'ponto'])

# values()
# Retorna uma lista (dict_values) que contém os valores de um dicionário.

dic_estudante = {"nome" : "Fulano",
"nota" : 8,
"ponto" : 1}

# values() -> retorna uma lista (dict_values) que contém os valores de um dicionário
valores = dic_estudante.values()
print(valores) # Vai exibir dict_values(['Fulano', 8, 1])

# items()
# Retorna uma lista (dict_items) que contém as chaves e valores de um dicionário.

dic_estudante = {"nome" : "Fulano",
"nota" : 8,
"ponto" : 1}

itens = dic_estudante.items()
print(itens)
# Vai exibir dict_items([('nome', 'Fulano'), ('nota', 8), ('ponto', 1)]

# dict()
# Função nativa para retornar uma cópia autônoma do dicionário.

dic_estudante = {"nome" : "Fulano",
"nota" : 8,
"ponto" : 1}

dic_copia = dict(dic_estudante)
print(dic_copia) # Vai exibir {'nome': 'Fulano', 'nota': 8, 'ponto': 1}

# copy()
# Também retorna uma cópia autônoma do dicionário. Use a que preferir.

dic_estudante = {"nome" : "Fulano",
"nota" : 8,
"ponto" : 1}

dic_copia = dic_estudante.copy()
print(dic_copia) # Vai exibir {'nome': 'Fulano', 'nota': 8, 'ponto': 1}

# Ao copiar um dicionário com copy() dicionários embutidos continuam apontadno pro mesmo objetos.

# del
# Exclui uma chave do dicionário.

dic_estudante = {"nome" : "Fulano",
"nota" : 8,
"ponto" : 1}

del dic_estudante["ponto"]

# pode também excluir todo o dicionário, como no código abaixo

del dic_estudante

# clear()
# Limpa um dicionário. Diferente do del, clear() limpa sem excluir o dicionário

dic_estudante = {"nome" : "Fulano",
"nota" : 8,
"ponto" : 1}

dic_estudante.clear()
print(dic_estudante)

"""# **CÓDIGOS**"""

# A. Dicionário de quadrados.

dic = {}
n = int(input())

i = 0
while len(dic) < n:
  for i in range(n):
    dic[i + 1] = (i + 1) * (i + 1)
    i = i + 1
    if len(dic) == n:
      break

for item in dic:
  print(f"{item}: {dic.get(item)}")

# B. Soma por categoria.

dic = {}

n = int(input())

i = 0
for i in range (n):
    categoria_valor = str(input()) # le exatamente as linhas
    i = i + 1
    categoria, valor = categoria_valor.split() # divide
    valor = int(valor) # converte

    if categoria in dic: # aqui verifica se existe
        dic[categoria] += valor # soma valores repetidos
    else:
        dic[categoria] = valor

for categoria, total in dic.items():
    print(f"{categoria}: {total}")

# C. Lista telefônica.

lista_telefonica = {}

entrada = str(input())

while entrada.lower() != "fim":
  nome, telefone = entrada.split()
  nome = nome.lower() # lower() transforma todas as letras de um uma string em minúsculas.
  lista_telefonica[nome] = telefone
  entrada = str(input())

consulta = input().lower()

if consulta in lista_telefonica:
    print(lista_telefonica[consulta])
else:
    print("Essa pessoa não está na lista telefônica")

# D. Agrupando por letra.

# dicionário vazio; armazena os nomes agrupados pela primeira letra;
# a chave é a letra em maiúculo; e o valor será uma lista com os nomes correspondentes;
grupos = {}

while True:
    nome = input()
    if nome.lower() == "fim": # se o usuário digitar "fim" (maiúsculo ou minúsculo), encerra o loop
        break

    # pega a primeira letra e muda para maiúscula
    letra = nome[0].upper()

    if letra in grupos:
        grupos[letra].append(nome) # se existir, adiciona o nome na lista correspondente
    else:
        grupos[letra] = [nome] # se não, só cria uma nova lista

# imprime na ordem alfabética das letras
for letra in sorted(grupos.keys()): # ordena as letras
    print(f"{letra}: {' '.join(grupos[letra])}") # une os elementos de uma lista em string.

# E. Contagem de letras na frase.

# Escreva um programa que recebe uma única frase como entrada e conta quantas vezes cada letra do alfabeto aparece, ignorando espaços, acentos e letras maiúsculas/minúsculas.
# Exiba as letras e suas contagens em ordem alfabética.

frase = input()

# armazena a contagem das letras
contagem = {}

# percorre cada caractere
for char in frase:
    if char.isalpha():  # verifica se é uma letra (inclui acentos)
        letra = char.upper()   # transforma em maiúscula para padronizar
        if letra in contagem:
            contagem[letra] += 1
        else:
            contagem[letra] = 1

# ordena e imprime
for letra in sorted(contagem.keys()):
    print(f"{letra}: {contagem[letra]}")

# F. Salários e valores.

# Faça um programa para ler cpf, nome, salário de 10 funcionários. Ao final da leitura, exibir os nomes e salários de quem tem salário abaixo e acima da média, nessa ordem.

cpfs = []
nomes = []
salarios = []

# le os dados dos 10 funcionarios
for _ in range(10):
    cpfs.append(input())
    nomes.append(input())
    salarios.append(float(input()))

# calcula a média dos salários
media = sum(salarios) / len(salarios) # sum() é pra somar todos os elementos

# exibe os funcionários abaixo da média
print("Abaixo da média:")
for i in range(10):
    if salarios[i] < media:
        print(f"{cpfs[i]} {nomes[i]}")

# exibe os funcionários acima da média
print("\nAcima da média:")
for i in range(10):
    if salarios[i] > media:
        print(f"{cpfs[i]} {nomes[i]}")