# -*- coding: utf-8 -*-
"""Resumo Estruturas de Repetição.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJQO4dbKQVcR8CvoeOllYFgBsz0rOaNT
"""

# Estruturas de Repetição
# Live 4

# while True (contadora) + break
number = 1
while True:
  print(number)
  number = number + 1
  if number > 10:
    break

# while + continue

i = 0
while i < 3:
   n = int(input("Insert a number: "))
   if n < 0:
      continue # pula a instrução de baixo e voltar pro início.
   i += 1

   # Esse código é um loop que pede números ao usuário até que ele tenha digitado 3 números não-negativos (ou seja, positivos ou o número zero).

# For (Acumuladora)
# Permite repetir uma quantidade indefinida de vezes, pois é baseado em uma condição.
# O laço For só permite repetir uma quantidade pré-definida de vezes. a qual é definida pela função 'range()'.

# Quando sabemos quantas vezes queremos que o código rode, é preferível usar o For.

for i in range(1,11):
  print("hello world") # Um loop que começa em 1 e termina em 11 é feito.

# O print será mostrado 10 vezes na tela.
# 1 significa o início, 11 o fim, e se adicionarmos mais um caractere a execução poderia pular, por exemplo, de dois em dois.
# se o range for básico "range(5)", ele apenas repete o que for pedido 5 vezes, seja uma string ou começar a contar.
# sempre iniciasse com 0, quando executado, se não dizer onde começar.

for letra in "texto":
  print(letra)

# for + listas.
# Este abaixo código percorre uma lista de números e imprime cada um deles em uma linha separada.

x = [3, 56, 80, 125]

for i in x:
  print(i)

# Resumo do colab sobre "Estruturas de Repetição".

# A resolução de problemas reais exige a repetição instruções até que um teste seja satisfeito ou uma quantidade de repetições seja alcançada.
# As estruturas de repetição (também chamadas de Laços ou Loops) podem ser de dois tipos: "while" ou "for".

# Existem dois tipos de variáveis frequentementeusadas em estruturas de repetição:

# Variáveis Contadoras = serve para contar coisas durante as voltas do laço (ex.: saber a quantidade de alunos de uma turma).
# baseada em valor CONSTANTE.

# Variável Acumuladora = serve para acumular/somar valores durante as voltas do laço (ex.: totalizar as notas dos alunos de uma turma).
# baseada em valor VARIÁVEL.

# LAÇO WHILE.
# usado para repetir um bloco de código enquanto a condição for verdadeira.

ctr = 0
while (ctr < 5):
    print(ctr)
    ctr += 1 # ctrl = ctr + 1 (mesma coisa)

# O código acima pode ser usado imprimir a seguinte sequência 0, 1, 2, 3, e 4 (um número em cada linha).
# A cada volta que o laço dá, +1 é somado à variável até que chegue a 4.

# BREAK.
# forma de encerrar o laço estando dentro do laço (sem ter que esperar voltar para o início do laço).

# CONTINUE.
# faz com que o laço pule para a próxima volta quando uma condição é verdadeira.

ctr= 0
while ctr < 5:
    ctr += 1 # ou ctr = ctr + 1
    if ctr%2 != 0: #pula para a próxima volta se o número for impar (se o resto da divisão por 2 for diferente de 0)
        continue
    print(ctr)
    cont = input("deseja continuar (S/N)?")
    if (cont == "N" or cont == "n"):
        break

# Isso aqui faz com que, enquanto a variável for menor que 5, some 1. E se o resto da divisão dela por dois for diferente de 0, ela continua, se não ela printa e pergutna se deseja continuar.

# O esquecimento da atualização de uma variável ou a má especificação de uma condição de parada do laço vai fazer com que o seu bloco de comandos seja repetido infinitamente, dando origem ao termo laço infinito.

# LAÇO FOR.
# Só permite repetir uma quantidade pré-definida de vezes, a qual é definida pela função "range()".
# Função range(): retorna uma sequência de números, começando em 0 por padrão, incrementando em 1 (por padrão) e parando antes de um número especificado.

# range(início, fim, passo) -> primeiro e último parametros são opcionais.
# Se os anteriores não forem formados, o inicio será 0 e o passo será de um em um.

# no exemplo abaixo, note que a variável x não precisa ser inicializada, pois isso é feito automaticamente pela função range().

for x in range(5):  # O valor inicial é 0 quando este não for informado
    print(x)

for x in range(0, 5):  # O valor inicial pode ser qualquer número
    print(x)

for x in range(1, 5, 2):  # Iniciando em 1 e incrementando de 2 em 2
    print(x)

"""# **Códigos passados no Dikastis.**"""

# Faça um programa que, dado um valor n, exiba os valores de 0 a n que são múltiplos de 3, de 5 e de ambos.

n = int(input())

for i in range(n + 1):
  if (i % 3 == 0 or i % 5 == 0) or (i % 3 == 0 and i % 5 == 0):
    if i % 3 == 0 and i % 5 == 0:
      print(f"{i} é múltiplo de 3 e de 5")
    elif i % 3 == 0:
      print(f"{i} é múltiplo de 3")
    elif i % 5 == 0:
      print(f"{i} é múltiplo de 5")

# Faça um programa que, dado um número, faça a contagem regressiva até 0 para saber a hora do lançamento de um foguete

n = int(input())

for i in range(n, -1, -1):
  print(i)
  if i == 0:
    print("O foguete decolou!")

# Faça um programa para ler o primeiro e último número de uma sequência e depois exibir: a somatória desses dois números, os números pares e os números ímpares dentro desse intervalo da sequência.

inicio = int(input())
ultimo = int(input())

soma = inicio + ultimo


print(f"A soma dos números é: {soma}")

print()

print("Os números pares dentro da sequência são:")
for i in range(inicio, ultimo + 1):
  if i % 2 == 0:
    print(f"{i}")

print()

print("Os números ímpares dentro da sequência são:")
for i in range(inicio, ultimo + 1):
  if i % 2 != 0:
    print(f"{i}")

# Escreva um programa que, dado um valor n, escreva a tabuada desse número (n x 1 até n x 10)

numero = int(input())
for i in range (1, 11):
  resultado = numero * i
  print(f"{numero} x {i} = {resultado}")

# Faça um programa para ler números inteiros e positivos até o usuário não desejar continuar informando um novo número. Ao final, o programa deve exibir o total de números lidos e a soma deles.

soma = 0
total = 0
confirm = str(input())

while confirm == "S" or confirm == "s":
    numero = float(input())
    soma += numero
    total += 1
    confirm = str(input())
if confirm  == "N" or confirm == "n":
      print(f"Você digitou {total} números")
      print(f"A soma final é: {soma:.2f}")

# Faça um programa que receba dois valores inteiros (a e b), e faça a divisão de a por b SEM UTILIZAR o operador / ou //.

a_maior = int(input())
b_menor = int(input())

resultado = 0

while a_maior >= b_menor:
  a_maior -= b_menor
  resultado += 1

print(resultado)

# Faça um programa que, dado um número inteiro n, imprima todos os termos da sequência de Fibonacci menores ou iguais a n, linha a linha.

termo = int(input())

a = 0
b = 1
proximo = 0

while a <= termo:
  print(a)
  proximo = a + b
  a = b
  b = proximo

# Escreva um programa que, dado um inteiro N, imprimir a sequência de Collatz começando com N até que o número chegue a 1. Cada número da sequência deve ser impresso em uma nova linha.

# A Sequência de Collatz é da seguinte forma:
# Se o número for par, divida-o por 2.
# Se o número for ímpar, multiplique-o por 3 e adicione 1.

n = int(input())
while n != 1:
  if n % 2 == 0:
    n = n // 2
  else:
    n = n * 3 + 1

  print(n)

# Faça um programa que, dado um saldo inicial, simule operações de depositar ou sacar.

saldo = float(input())
saldo_inicial = saldo
operacao = str(input())


while operacao == "sacar" or operacao == "depositar":
  if operacao == "sacar":
    saque = float(input())
    saldo = saldo - saque
    saldo_atual = saldo
    operacao = str(input())
  elif operacao == "depositar":
    deposito = float(input())
    saldo = saldo + deposito
    saldo_atual = saldo
    operacao = str(input())

if operacao == "sair":
  print(f"Seu saldo era: R$ {saldo_inicial:.2f}")
  print(f"Seu novo saldo é: R$ {saldo_atual:.2f}")

# Escreva um programa que recebe um número inteiro n e imprime Sim se ele for um número primo, ou Não caso contrário.

n = int(input())

primo = True

for i in range(2, n):
    if n % i == 0:
        primo = False
        break
if primo and n > 1:
    print("Sim, esse número é primo")
else:
    print("O número não é primo")