# -*- coding: utf-8 -*-
"""Códigos da Lista de Estruturas de Decisão.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17FScyK6tmTa6Ae8Gc-r8ujQm-FAYpbSK
"""

caractere = str(input())
vogal = ("a", "e", "i", "o", "u", "A", "E", "I", "O", "U")
opera_matematica = ("+", "*","-", "/", "//", "**")

if caractere in vogal: # não se usa = (atribuir valor) e == (igualdade) aqui. "in" se encaixa melhor.
  print("O caractere é uma vogal")
elif caractere.isnumeric(): # verifica se todos os caracteres em uma string são numéricos
  print("O caractere é um número")
else:
  print("O caractere é uma operação matemática")

n1 = float(input())
n2 = float(input())
operacao = str(input())

if operacao == "+":
  soma = n1 + n2
  print(f"Você escolheu a operação de adição. O resultado dessa adição é {soma:.2f}")
elif operacao == "-":
  subtracao = n1 - n2
  print(f"Você escolheu a operação de subtração. O resultado dessa subtração é {subtracao:.2f}")
elif operacao == "*":
  multiplicar = n1 * n2
  print(f"Você escolheu a operação de multiplicação. O resultado dessa multiplicação é {multiplicar:.2f}")
elif operacao == "/":
  dividir = n1 / n2
  print(f"Você escolheu a operação de divisão. O resultado dessa divisão é {dividir:.2f}")

nome = str(input())
sobrenome = str(input())
idade = int(input())
nome_completo = nome + " " + sobrenome

if idade < 12:
  print(f"A categoria do atleta {nome_completo} é a infantil.")
elif idade == 12 or idade <= 17:
  print(f"A categoria do atleta {nome_completo} é a juvenil.")
elif idade == 18 or idade <= 35:
  print(f"A categoria do atleta {nome_completo} é a adulta.")
elif idade > 35:
  print(f"A categoria do atleta {nome_completo} é a master.")

valor_diaria = float(input())
dias_trabalhados = int(input())
salario_bruto = valor_diaria * dias_trabalhados

if salario_bruto <= 2000:
  print("Você está isento do Imposto de Renda.")
  print(f"Seu salário é: R$ {salario_bruto:.2f}")
elif salario_bruto > 2000 and salario_bruto<= 5000:
  imposto_de_renda = salario_bruto * 0.15
  salario_liquido = salario_bruto - imposto_de_renda
  print("Você não está isento do Imposto de Renda.")
  print(f"Seu salário bruto é de: R$ {salario_bruto:.2f}")
  print(f"Seu valor do IR é: R$ {imposto_de_renda:.2f}")
  print(f"Seu salário líquido é de: R$ {salario_liquido:.2f}")
elif salario_bruto > 5000:
  imposto_de_renda = salario_bruto * 0.275
  salario_liquido = salario_bruto - imposto_de_renda
  print("Você não está isento do Imposto de Renda.")
  print(f"Seu salário bruto é de: R$ {salario_bruto:.2f}")
  print(f"Seu valor do IR é: R$ {imposto_de_renda:.2f}")
  print(f"Seu salário líquido é de: R$ {salario_liquido:.2f}")

media_salarial = float(input())
nome_funcionario = str(input())
salario_funcionario = float(input())
resultado_diferença = salario_funcionario - media_salarial

if salario_funcionario > media_salarial:
  print(f"{nome_funcionario} recebe R$ {resultado_diferença:.2f} a mais do que a média salarial da empresa.")
elif salario_funcionario < media_salarial:
  print(f"{nome_funcionario} recebe R$ {resultado_diferença:.2f} a menos do que a média salarial da empresa.")
elif salario_funcionario == media_salarial:
  print(f"{nome_funcionario} recebe igual a média salarial da empresa.")

# Programa para ler lados de uma triângulo.
# Escreva um programa para ler o tamanho de três segmentos de retas e informar se estas podem formar um triângulo (a soma de quaisquer dois lados sempre deve ser maior que o terceiro lado).
# Caso sim, também deve-se informar se este é equilátero (tem os três lados iguais), escaleno (tem os três lados diferentes) ou isósceles (tem apenas dois lados iguais).

lado1 = int(input())
lado2 = int(input())
lado3 = int(input())

if (lado1 + lado2) > lado3 and (lado3 + lado2) > lado1 and (lado3 + lado1) > lado2:
  if lado1 == lado2 == lado3:
    print("Triangulinho com todos os lados iguais: é equilátero!!")
  elif lado1 != lado2 != lado3:
    print("Tem os três lados diferentes mas ainda continua sendo um triangulinho: é escaleno!!")
  elif lado1 == lado2 or lado2 == lado3 or lado3 == lado1:
    print("Triangulinho com dois lados iguais: é isósceles!!")
else:
  print("Esses segmentos de reta não formam um triângulo. Tchau!!!!")

# Faça um programa para ler quatro números inteiros (n1, n2, n3 e n4) e depois exibir todos que são pares e positivos, pares e negativos, ímpares e positivos, ímpares e negativo e zero, nesta ordem.

n1 = int(input())
n2 = int(input())
n3 = int(input())
n4 = int(input())
numeros = (n1, n2, n3, n4) # Colocando todas as entradas em um único grupo.

pares_positivos = [] # Criando listas.
pares_negativos = []
impares_positivos = []
impares_negativos = []
zeros = []

for numero in numeros: # A conjunto "numeros" está sendo percorrido, e de acordo com a estrutura de repetição, os números vão sendo adicionados em uma lista especifica.
  if numero % 2 == 0 and numero > 0:
    pares_positivos.append(numero) # nome_da_lista.append(item_que_voce_quer_adicionar)
  elif numero  % 2 == 0 and numero < 0:
    pares_negativos.append(numero)
  elif numero % 2 != 0 and numero > 0:
    impares_positivos.append(numero)
  elif numero  % 2 != 0 and numero < 0:
    impares_negativos.append(numero)
  elif numero  == 0:
    zeros.append(numero)

print("Números pares e positivos:") # aqui impreme esse coiso na tela
for numero in pares_positivos: # aqui pega os numeros da lista, ou o nada
    print(numero) # e aqui bota na tela

print("Números pares e negativos:")
for numero in pares_negativos:
    print(numero)

print("Números ímpares e positivos:")
for numero in impares_positivos:
    print(numero)

print("Números ímpares e negativos:")
for numero in impares_negativos:
    print(numero)

print("Números zeros:")
for numero in zeros:
    print(numero)