# -*- coding: utf-8 -*-
"""Códigos da Lista de Listas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11YvKxt3eBjPsXLSRg4nF0pohQACTrqAM
"""

# A. Número elevados a expoente.
# Faça um programa que receba 10 números digitados pelo usuário e, em seguida, leia um expoente. O programa deve criar e imprimir uma nova lista com cada número elevado ao expoente informado.

lista_numeros = [] # criei a lista


while len(lista_numeros) < 10: # criei o laço while para determinar até quantos números eu vou adicionar
  numero = float(input()) # inputar né.
  lista_numeros.append(numero) # adicionar os numeros a lista.

expoente = int(input())

for n in lista_numeros[:]: # percorre somente os 10 números.1
  print(f"{n**expoente:.2f}") # imprime com uma formatação que os deixa elevados ao expoente.
  # e também os deixa com duas casas decimais.

# B. Ranking de notas.
# Faça um programa que leia o nome e a nota de vários alunos (a entrada termina quando for digitado um nome vazio OU quando a entrada for "fim").
# Armazene os nomes em uma lista e as notas em outra.
# Em seguida, exiba os nomes dos alunos ordenados da maior para a menor nota.

lista_notas = []
lista_alunos = []

nome = str(input())
if nome != "" and nome != "fim":
  lista_alunos.append(nome)

while nome != "fim" and nome != "":
  nota = float(input())
  lista_notas.append(nota)
  nome = str(input())
  if nome != "" and nome != "fim":
    lista_alunos.append(nome)

alunos_notas = list(zip(lista_notas, lista_alunos)) # emparelha as listas, transoforma
# em uma lista só e iguala atribui a uma nova lista.

alunos_notas.sort(reverse = True) # ordena e inverte, para ficar do maior para o menor.

if nome == "fim" or nome == "":
   for nota, aluno in alunos_notas:
        print(f"{aluno}: {nota:.2f}")

# C. Quantos maiores que a média?
# Dada uma lista de n números, calcule a média aritmética e conte quantos elementos são maiores do que ela.

n = []

elementos = input()
numeros = elementos.split() # método para dividir a string em várias partes.
# numeros é uma lista agora

for numero in numeros:
    n.append(int(numero)) # percorre a lista numeros e depois adiciona os elementos como inteiro na lista n.

soma = 0
for numero in n: # aqui se faz o calculo da média, de praxe.
    soma = soma + numero

media = soma / len(n)

contador = 0
for numero in n:
    if numero > media:
        contador = contador + 1

print(contador)

# D. Quantos pares? Quantos ímpares?

# Escreva um programa em Python que permita ao usuário digitar uma quantidade indeterminada de números inteiros, um por vez. Depois, o programa deverá exibir a quantidade de números digitados, a quantidade de números pares e a quantidade de números ímpares.

lista_par = []
lista_impar = []
total = []


soma_par = 0
soma_impar = 0

numero = int(input())
total.append(numero)

if numero % 2 == 0:
    lista_par.append(numero)
    soma_par = soma_par + numero

else:
    lista_impar.append(numero)
    soma_impar = soma_impar + numero

confirmacao = str(input())

while confirmacao == "s" or confirmacao == "S":
  numero = int(input())
  20total.append(numero)
  if numero % 2 == 0:
    lista_par.append(numero)
    soma_par = soma_par + numero
  else:
    lista_impar.append(numero)
    soma_impar = soma_impar + numero

  confirmacao = str(input())

print(f"Quantidade de números digitados: {len(total)}")
print(f"Soma dos números pares: {soma_par}")
print(f"Soma dos números ímpares: {soma_impar}")

# E. Contabilidades.

# Faça um programa que leia os nomes (sem repetição), os preços de compra e os percentuais de lucro de 5 produtos. Após a leitura, exiba para cada produto seu nome, o preço de compra e o preço de venda calculado.

lista_produto = []
lista_precos = []
lista_lucro_perc = []
produtos = []

while len(lista_produto) < 5:
  nome_produto = str(input())
  preco_compra = float(input())
  percentual_lucro = float(input())

  lista_produto.append(nome_produto)
  lista_precos.append(preco_compra)
  lista_lucro_perc.append(percentual_lucro)

  if len(lista_produto) == 5:
    break

produtos = list(zip(lista_produto, lista_precos, lista_lucro_perc))


if len(produtos) == 5:
  for nome, preco_compra, percentual_lucro in produtos:
    lucro = preco_compra * (percentual_lucro / 100)
    preco_venda = preco_compra + lucro
    print(f"{nome}: Compra = R${preco_compra:.2f}, Venda = R${preco_venda:.2f}")

# F. Quantidade de elementos.

# Escreva um programa que recebe valores para serem adicionados numa lista. Após isso, o programa deverá exibir quantas vezes os valores aparecem dentro da lista.

valores = []


n = float(input())
valores.append(n)
confirmacao = str(input())

while confirmacao == "s" or confirmacao == "S":
  n = float(input())
  valores.append(n)
  confirmacao = str(input())

vistos = [] # pra guardar os elementos já vistos1
if confirmacao != "s" or confirmacao != "S":
  for elemento in valores:
    if elemento not in vistos:
      print(f"O elemento {elemento} aparece {valores.count(elemento)} vezes na lista")
      vistos.append(elemento)

# G. k-sésimo maior valor. #-----QUESTÃO ERRADA---#

t = int(input())  # tamanho da lista

valores = []
for i in range(t):
    n = int(input())  # lê cada número
    valores.append(n)

k = int(input())  # índice desejado

valores.sort()  # organiza a lista em ordem crescente

print(valores[k]) # PRINTA O VALOR QUE ESTÁ NO ÍNDICE

# H. Multiplique por K.

# Dada uma lista de n números inteiros e um valor inteiro k, crie uma nova lista com os elementos multiplicados por k e imprima o resultado.


elementos = str(input()).split()

k = int(input())

for elemento in elementos:
  print(int(elemento) * k, end=' ')

# I. Listinha de Compras.

lista_compras = []

item = str(input())

while item != "fim":
  lista_compras.append(item)
  item = str(input())

lista_compras.sort()

for item in lista_compras:
    print(item)

# J. Palavras que começam com vogal

vogais = "aeiouAEIOU"
palavras_com_vogal = []

confirmacao = str(input())

while confirmacao != "fim":
    palavra =
    if palavra[0] in vogais:
        palavras_com_vogal.append(palavra)
    confirmacao = input()

if len(palavras_com_vogal) == 0:
    print("Nenhuma palavra digitada começa com vogal.")
else:
    for palavra in palavras_com_vogal:
        print(palavra)

# J. Palavras que começam com vogal

vogais = "aeiouAEIOU"
palavras_com_vogal = []

while True:
    palavra = input()
    if palavra == "fim":
        break
    if palavra[0] in vogais: # verifica se começa com vogal.
        palavras_com_vogal.append(palavra)

if len(palavras_com_vogal) == 0:
    print("Nenhuma palavra digitada começa com vogal.")
else:
    for palavra in palavras_com_vogal:
        print(palavra)