# -*- coding: utf-8 -*-
"""Código da Lista de Funções.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yyqf5du0QqC6gpJWWvj86WYaHdVHqld3
"""

# A. N elevado a X.

# Escreva uma função que receba dois parâmetros: numero e potencia. O retorno dessa função deve ser o numero elevado à potência

def potenciacao():
  numero = float(input())
  potencia = int(input())
  print(f"{numero ** potencia:.2f}")

potenciacao()

# B. Média de 3.

# Escreva uma função chamada media(a, b, c) que recebe três números como argumentos e retorna a média aritmética entre eles.

def media_abc ():
 n1 = float(input())
 n2 = float(input())
 n3 = float(input())
 soma = n1 + n2 + n3
 print(f"{soma / 3:.2f}")

media_abc()